name: Build vMagisk Module

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 # Update ke v4

      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Compile vmeerd with ndk-build
        run: |
          ndk-build -C ./jni \
          NDK_PROJECT_PATH=. \
          APP_BUILD_SCRIPT=./jni/Android.mk \
          APP_ABI=arm64-v8a \
          APP_PLATFORM=android-21

      - name: Prepare Magisk Module Structure
        run: |
          mkdir -p system/bin
          cp libs/arm64-v8a/vmeerd system/bin/
          rm -rf libs obj
          chmod +x service.sh
          chmod +x system/bin/vmeerd

      - name: Zip Magisk Module
        run: |
          zip -r vMagisk-Module.zip . -x "*.git*" ".github*" "jni*"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4 # WAJIB Update ke v4
        with:
          name: vMagisk-Release
          path: vMagisk-Module.zip
          compression-level: 9 # Opsional: kompresi maksimal
